PREFIX dbo:  <http://dbpedia.org/ontology/>
PREFIX dbr:  <http://dbpedia.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?city ?cityName
WHERE {
  ?city a dbo:City ;
        dbo:country ?country ;
        rdfs:label ?cityName .
  FILTER (?country IN (dbr:United_Kingdom, dbr:England, dbr:Scotland,
                       dbr:Wales, dbr:Northern_Ireland))
  FILTER (LANG(?cityName) = "en")
}
ORDER BY ?cityName
